FROM node:16.13.2

# ARG PKG="sudo git vim curl zip unzip locales ${TMP_PKG}"

# SHELL ["/bin/bash", "-c"]

# RUN apt-get update \
#   && apt-get install -y ${PKG} \
  # && groupadd --gid ${USER_GID} ${USER_GROUP_NAME} \
  # && useradd --uid ${USER_UID} --shell /bin/bash --gid ${USER_GID} -m ${USERNAME} \
  # && echo %${USER_GROUP_NAME} ALL=\(ALL\) NOPASSWD:ALL > /etc/sudoers.d/${USER_GROUP_NAME} \
  # && chmod 0440 /etc/sudoers.d/${USER_GROUP_NAME}